# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-19 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='posted_by',
        ),
        migrations.AddField(
            model_name='quote',
            name='posted_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.User'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quote',
            name='user_fav',
        ),
        migrations.AddField(
            model_name='quote',
            name='user_fav',
            field=models.ManyToManyField(related_name='favorite_quotes', to='quotes.User'),
        ),
    ]
